name: goreleaser

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Lowercase registry namespace
        run: echo "DOCKER_REGISTRY_NAMESPACE=${DOCKER_REGISTRY_NAMESPACE,,}" >> $GITHUB_ENV
      - name: Set GORELEASER_PREVIOUS_TAG
        if: ${{ !contains(github.ref, '-nightly') }}
        run: |
          prev_tag=$(git tag | grep -v "nightly" | sort -r --version-sort | head -n 2 | tail -n 1)
          echo "GORELEASER_PREVIOUS_TAG=$prev_tag" >> $GITHUB_ENV
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: ghcr.io
          DOCKER_REGISTRY_NAMESPACE: ${{ github.repository_owner }}
          GORELEASER_CURRENT_TAG: ${{ github.ref_name }}
